// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

export const AWS_CONFIG =  {
    "aws_appsync_graphqlEndpoint": "https://zowj6ydbovabbmgcrnt2i5mqkq.appsync-api.cn-north-1.amazonaws.com.cn/graphql",
    "aws_appsync_region": "cn-north-1",
    "aws_appsync_authenticationType": "AWS_IAM",
    "aws_appsync_apiKey": "null",
};
